spring.application.name=eballotUk

spring.profiles.active=local

# Enable Actuator Metrics & Prometheus Endpoint
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=health,prometheus,info

# Enable Health Probes for Kubernetes or Liveness/Readiness Checks
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true